# URLS
CAP_SOLVER_URL_CREATE_TASK = 'https://api.capsolver.com/createTask'
CAP_SOLVER_URL_CHECK_RESULT = 'https://api.capsolver.com/getTaskResult'

# Generic request keys
CAP_SOLVER_REQUEST_KEY_API_TOKEN = 'clientKey'
CAP_SOLVER_REQUEST_KEY_TASK = 'task'
CAP_SOLVER_REQUEST_KEY_TASK_ID = 'taskId'

# Generic response keys
CAP_SOLVER_RESPONSE_KEY_ERROR_ID = 'errorId'
CAP_SOLVER_RESPONSE_KEY_ERROR_CODE = 'errorCode'
CAP_SOLVER_RESPONSE_KEY_TASK_ID = 'taskId'
CAP_SOLVER_RESPONSE_KEY_STATUS = 'status'
CAP_SOLVER_RESPONSE_KEY_SOLUTION = 'solution'

CAP_SOLVER_RESPONSE_STATUS_IDLE = 'idle'
CAP_SOLVER_RESPONSE_STATUS_PROCESSING = 'processing'
CAP_SOLVER_RESPONSE_STATUS_READY = 'ready'

# Generic task proxy keys
CAP_SOLVER_TASK_KEY_PROXY_TYPE = 'proxyType'
CAP_SOLVER_TASK_KEY_PROXY_ADDRESS = 'proxyAddress'
CAP_SOLVER_TASK_KEY_PROXY_PORT = 'proxyPort'
CAP_SOLVER_TASK_KEY_PROXY_USERNAME = 'proxyLogin'
CAP_SOLVER_TASK_KEY_PROXY_PASSWORD = 'proxyPassword'

# Generic task keys
CAP_SOLVER_TASK_KEY_CAPTCHA_TYPE = 'type'
CAP_SOLVER_TASK_KEY_WEBSITE_URL = 'websiteURL'

# HCaptcha task keys
CAP_SOLVER_TASK_TYPE_H_CAPTCHA = 'HCaptchaTaskProxyLess'
CAP_SOLVER_TASK_TYPE_H_CAPTCHA_PROXY = 'HCaptchaTask'

CAP_SOLVER_TASK_H_CAPTCHA_SITE_KEY = 'websiteKey'
CAP_SOLVER_TASK_H_CAPTCHA_INVISIBLE = 'isInvisible'

CAP_SOLVER_RESPONSE_H_CAPTCHA_RESPONSE_KEY = 'gRecaptchaResponse'
CAP_SOLVER_RESPONSE_H_CAPTCHA_REQUEST_KEY = 'captchaKey'
CAP_SOLVER_RESPONSE_H_CAPTCHA_USER_AGENT = 'userAgent'