# URLS
TWO_CAPTCHA_URL_CREATE_TASK = 'https://api.2captcha.com/createTask'
TWO_CAPTCHA_URL_CHECK_RESULT = 'https://api.2captcha.com/getTaskResult'

# Generic request keys
TWO_CAPTCHA_REQUEST_KEY_API_TOKEN = 'clientKey'
TWO_CAPTCHA_REQUEST_KEY_TASK = 'task'
TWO_CAPTCHA_REQUEST_KEY_TASK_ID = 'taskId'

# Generic response keys
TWO_CAPTCHA_RESPONSE_KEY_ERROR_ID = 'errorId'
TWO_CAPTCHA_RESPONSE_KEY_TASK_ID = 'taskId'
TWO_CAPTCHA_RESPONSE_KEY_STATUS = 'status'
TWO_CAPTCHA_RESPONSE_KEY_SOLUTION = 'solution'

TWO_CAPTCHA_RESPONSE_STATUS_PROCESSING = 'processing'
TWO_CAPTCHA_RESPONSE_STATUS_READY = 'ready'

# Generic task proxy keys
TWO_CAPTCHA_TASK_KEY_PROXY_TYPE = 'proxyType'
TWO_CAPTCHA_TASK_KEY_PROXY_ADDRESS = 'proxyAddress'
TWO_CAPTCHA_TASK_KEY_PROXY_PORT = 'proxyPort'
TWO_CAPTCHA_TASK_KEY_PROXY_USERNAME = 'proxyLogin'
TWO_CAPTCHA_TASK_KEY_PROXY_PASSWORD = 'proxyPassword'

# Generic task keys
TWO_CAPTCHA_TASK_KEY_CAPTCHA_TYPE = 'type'
TWO_CAPTCHA_TASK_KEY_WEBSITE_URL = 'websiteURL'

# FunCaptcha task keys
TWO_CAPTCHA_TASK_TYPE_FUN_CAPTCHA = 'FunCaptchaTaskProxyless'
TWO_CAPTCHA_TASK_TYPE_FUN_CAPTCHA_PROXY = 'FunCaptchaTask'

TWO_CAPTCHA_TASK_FUN_CAPTCHA_PUBLIC_KEY = 'websitePublicKey'
TWO_CAPTCHA_TASK_FUN_CAPTCHA_SUBDOMAIN = 'funcaptchaApiJSSubdomain'
TWO_CAPTCHA_TASK_FUN_CAPTCHA_USER_AGENT = 'userAgent'

TWO_CAPTCHA_RESPONSE_FUN_CAPTCHA_TOKEN = 'token'

# HCaptcha task keys
TWO_CAPTCHA_TASK_TYPE_H_CAPTCHA = 'HCaptchaTaskProxyless'
TWO_CAPTCHA_TASK_TYPE_H_CAPTCHA_PROXY = 'HCaptchaTask'

TWO_CAPTCHA_TASK_H_CAPTCHA_SITE_KEY = 'websiteKey'
TWO_CAPTCHA_TASK_H_CAPTCHA_INVISIBLE = 'isInvisible'

TWO_CAPTCHA_RESPONSE_H_CAPTCHA_RESPONSE_KEY = 'token'
TWO_CAPTCHA_RESPONSE_H_CAPTCHA_REQUEST_KEY = 'respKey'
TWO_CAPTCHA_RESPONSE_H_CAPTCHA_USER_AGENT = 'userAgent'

